Repository VIDA-NYU/UrbanMapper, pull requests merged in 2025-05, with the labels that each got.

#50 refactor(docs): add contributing troubleshooting section
  docs/CONTRIBUTING.md
Labels: bug, documentation

#49 Add support for loading datasets from Hugging Face using from_huggingface_oscur
  docs/api/loaders.md
  docs/user-guide/modules/1-loaders.md
  examples/Basics/[1]loader.ipynb
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  src/urban_mapper/modules/loader/loader_factory.py
Labels: loader

#54 Can @overturemaps be used as an `Urban Layer`?
  docs/getting-started/examples.md
  examples/Study Cases/Overture/[1] overture_pipeline.ipynb
  examples/Study Cases/Overture/[2] overture_pipeline_advanced.ipynb
Labels: documentation, examples

#57 Update installation instructions to reflect PyPI availability
  README.md
  docs/CONTRIBUTING.md
  docs/getting-started/installation.md
Labels: documentation

#58 Fix/mermaid support doc
  docs/CONTRIBUTING.md
  docs/user-guide/modules/7-pipelines.md
  mkdocs.yml
  pyproject.toml
  requirements-dev.txt
  src/urban_mapper/pipeline/pipeline.py
Labels: bug, documentation
